# <center>Laboratorium 1<br>Metody Numeryczne</center>

Biblioteki niezbędne do wykonania zadania:

(wykonanie tego bloku zapewnia do nich dostęp w kolejnych blokach)

In [112]:
import main

import numpy as np
import scipy

Przydatne w trakcie zajęć mogą okazać się metody macierzy z pakietu Numpy, takie jak na przykład długość wektora - *[len]()* czy rozmiar macierzy -
*[shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape)*. Poniższy kod ilustruje ich podstawowe działanie. Dodatkowe metody obiektu $ndarray$ można znaleźć w oficjalnej *[dokumentacji](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)*.

In [113]:
vector = np.array([1, 2, 3])
print('Wektor:')
print(vector)
print('Długość:', len(vector))
print('Rozmiar:', vector.shape, '\n')

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Macierz:')
print(matrix)
print('Rozmiar:', matrix.shape)

Wektor:
[1 2 3]
Długość: 3
Rozmiar: (3,) 

Macierz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rozmiar: (3, 3)


***Zadanie 1.***  
Zaimplementuj funkcję $cylinder\_area$ tak by zwracała pole powierzchni walca o promieniu podstawy $r$ i wysokości $h$. Stała $\pi$ jest zdefiniowana np. w bibliotece *[math](https://docs.python.org/3/library/math.html#constants)*. Jeżeli nie da się policzyć pola funkcja powinna zwracać wartość *NaN*. Sprawdź działanie zaimplementowanej funkcji dla dowolnych wartości w tym notatniku.

In [114]:
print("Pola powierzchni walców:\n")
#Dodatnie argumenty
r = 5.3
h = 7.45
print("r = 5.3 oraz h = 7.45: ", main.cylinder_area(r, h))

#Argument równy zero
r = 0
h = 3.56
print("r = 0 oraz h = 3.56: ", main.cylinder_area(r, h))

#Argument ujemny - nieprawidłowe dane
r = -1
h = 3
print("r = -1 oraz h = 3: ", main.cylinder_area(r, h))

Pola powierzchni walców:

r = 5.3 oraz h = 7.45:  424.58624713266056
r = 0 oraz h = 3.56:  0.0
r = -1 oraz h = 3:  nan


Wniosek:

Zaimplementowana funkcja $cylinder_area$ oblicza pole powierzchni całkowitej walca o zadanych parametrach $r$ oraz $h$. W przypadku podania ujemnej wartości któregoś z parametrów funkcja poprawnie zwraca wartość nieokreśloną NaN.

***Zadanie 2.***  
Wygeneruj dowolne ciągi arytmetyczny o kroku różnym od jeden i niebędącym liczbą całkowitą, używając w tym celu funkcji *[arange](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)* oraz *[linspace](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linspace.html)*. Wypisz go i przeanalizuj otrzymane rezultaty.

In [115]:
x = np.arange(0, 5.2, 0.2)
y = np.linspace(0, 10, 21)
print("Ciąg od 0 do 5.2 z krokiem 0.2: \n", x)
print("\nCiąg od 0 do 10 podzielony na 21 części w równych odstępach: \n", y)

Ciąg od 0 do 5.2 z krokiem 0.2: 
 [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5. ]

Ciąg od 0 do 10 podzielony na 21 części w równych odstępach: 
 [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


Wniosek:

Ciągi zostały wygenerowane za pomocą funkcji $arange$ oraz $linspace$. Wynik otrzymany za pomocą funkcji $arange$ nie uwzględnia końca wybranego przedziału (przedział otwarty prawostronnie). Funkcja $linspace$ natomiast dzieli wybrany przedział na równe części uwzględniając jego koniec (przedział obustronnie domknięty).

W przypadku generowania ciągu z krokiem innym niż całkowity lepszym rozwiązaniem jest wygenerowanie ciągu funkcją $linspace$.

***Zadanie 3.***  
Zaimplementuj funkcję $fib$ zwracającą wektor pierszych n elementów *[ciągu Fibonnaciego](https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego)*, jeżeli nie jest to możliwe funkcja powinna zwrócić wartość *None*.

In [116]:
#1
print("Ciąg Fibonacciego dla dodatnich wartości argumentu n:")
print("n = 55: ", main.fib(55))
print("n = 1: ", main.fib(1))
print("n = 2: ", main.fib(2))

#2
print("\nn = 0: ", main.fib(0))

#3
print("\nUjemne n = -5: ", main.fib(-5))

#4
print("\nWymierne n = 9.56: ", main.fib(9.56))

Ciąg Fibonacciego dla dodatnich wartości argumentu n:
n = 55:  [[          1           1           2           3           5           8
           13          21          34          55          89         144
          233         377         610         987        1597        2584
         4181        6765       10946       17711       28657       46368
        75025      121393      196418      317811      514229      832040
      1346269     2178309     3524578     5702887     9227465    14930352
     24157817    39088169    63245986   102334155   165580141   267914296
    433494437   701408733  1134903170  1836311903 -1323752223   512559680
   -811192543  -298632863 -1109825406 -1408458269  1776683621   368225352
   2144908973]]
n = 1:  [1]
n = 2:  [1 1]

n = 0:  None

Ujemne n = -5:  None

Wymierne n = 9.56:  None


Wniosek:

Zaimplementowana funkcja $fib$ bezproblemowo oblicza ciąg Fibonacciego nawet dla wartości większych od 55, co byłoby niemal niemożliwe przy użyciu klasycznej rekurencji, a następnie wypisuje wynik w postaci obiektu klasy $ndarray$.

W przypadku podania argumentu równego 0, argumentu ujemnego bądź wymiernego funkcja poprawnie zwraca wartość nieokreśloną None.

***Zadanie 4.***  
Napisz funkję $matrix\_calculations$ która jako argument przyjmuje dowolną wartość liczbową *a* i tworzy macierz:  
  
$\mathbf{M} =\left[ \begin{matrix}
a & 1 & -a\\
0 & 1 & 1\\
-a & a & 1
\end{matrix}\right]
$    
   
Dla zadeklarowanej macierzy wyznacz numerycznie macierz odwrotną $\mathbf{Minv}$ (jeżeli nie istnieje taka macierz wartość wynosi NaN), macierz transponowaną $\mathbf{Mt}$ i wyznacznik macierzy $\mathbf{Mdet}$. Zwróć otrzymane wartości w postaci krotki postaci $(\mathbf{Minv}, \mathbf{Mt}, \mathbf{Mdet})$.  Wypisz otrzymane wyniki. 
  
***Wskazówki:*** Do tworzenia obiektów mających własności macierzy w języku Python używa się klasy *[array](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.array.html)* z pakietu *[numpy](http://www.numpy.org/)*, przykładowe użycie:

In [117]:
import numpy as np # słowo kluczowe "as" oznacza przesłania nazwę numpy i pozwala  
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
A = np.array([[1,2],[3,4]])
print("Wektor poziomy:\n {0}".format(a))
print("Wektor pionowy:\n {0}".format(b))
print("Macierz:\n {0}".format(A))

Wektor poziomy:
 [1 2 3]
Wektor pionowy:
 [[1]
 [2]
 [3]]
Macierz:
 [[1 2]
 [3 4]]


Do wykonania operacji odwracania macierzy należy użyć funkcji *[inv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)*, do obliczenia wyznacznika macierzy stosuje się funkcję *[det](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linalg.det.html)*  z bliblioteki *[linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)*. Natomiast transpozycję macierzy wykonujemy przez funkcję *[transpose](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.transpose.html)* której skrucona wersja to $M.T$ z pakietu *numpy*.  
    
*Ciekawostka:* Python natywnie nie zawiera struktury danych typu tablica, na poziomie języka jest to rozwiązane poprzez strukturę listy list do której elementów odwołuje się poprzez indeksy jak w C/C++.

In [118]:
Minv, Mt, Mdet = main.matrix_calculations(5)

print('Argument równy 5.')
print('Macierz odwrotna: \n', Minv)
print('Transpozycja macierzy: \n', Mt)
print('Wyznacznik macierzy: ', Mdet)

Minv, Mt, Mdet = main.matrix_calculations(0)

print('\nArgument równy 0.')
print('Macierz odwrotna: \n', Minv)
print('Transpozycja macierzy: \n', Mt)
print('Wyznacznik macierzy: ', Mdet)

Argument równy 5.
Macierz odwrotna: 
 [[ 0.08  0.52 -0.12]
 [ 0.1   0.4   0.1 ]
 [-0.1   0.6  -0.1 ]]
Transpozycja macierzy: 
 [[ 5  0 -5]
 [ 1  1  5]
 [-5  1  1]]
Wyznacznik macierzy:  -49.99999999999997

Argument równy 0.
Macierz odwrotna: 
 nan
Transpozycja macierzy: 
 [[0 0 0]
 [1 1 0]
 [0 1 1]]
Wyznacznik macierzy:  0.0


Wniosek:

Napisana funkcja $matrix_calculations$ korzystając z wbudowanych funkcji $inv$, $det$ oraz $transpose$ poprawnie tworzy macierz oraz wykonuje zadane operacje. Funkcja najpierw liczy wyznacznik, aby w przypadku $Mdet$ równego 0 zwrócić wartość nieokreśloną None w miejsce macierzy odwrotnej.

***Zadanie 5.***  
Stwórz w noataniku macierz:  
$\mathbf{M} =\left[ \begin{matrix}
3 & 1 & -2 & 4\\
0 & 1 & 1 & 5\\
-2 & 1 & 1 & 6\\
4 & 3 & 0 & 1\\
\end{matrix}\right]
$   
Wypisz przy pomocy funkcji *print* następujące elementy macierzy $\mathbf{M}$: $\mathbf{M}_{1,1},\mathbf{M}_{3,3},\mathbf{M}_{3,2}$. Zdefiniuj wektor $\mathbf{w1}$ którego elementy to trzecia kolumna macierzy $\mathbf{M}$ oraz wektor $\mathbf{w2}$ który składa się z drugiego wiersza tej macierzy.  
  
***Wskazówki:***
Tablice z pakietu *numpy* są indeksowane od zera a do każdego elementu można odwołać się poprzez jego indeks. Przykład użycie


In [119]:
# Inicjalizacja macierzy do przykładu
P = np.array([[1,3,2],[3,4, 6],[7,8,9]])
print("Macierz P=\n{0}".format(P))
# wyciągnięcie trzeciej kolumny 
wektor1 = P[:,2]
# wyciągnięcie trzeciego wiersza 
wektor2 = P[2,:]
print("Elementy trzeciej kolumny:\n {0}".format(wektor1))
print("Elementy trzeciego wiersza:\n {0}".format(wektor2))

Macierz P=
[[1 3 2]
 [3 4 6]
 [7 8 9]]
Elementy trzeciej kolumny:
 [2 6 9]
Elementy trzeciego wiersza:
 [7 8 9]


Dodatkowo twórcy biblioteki umożliwiają użytkownikowi na manipulację elementami tablicy poprzez operator ':', więcej szczegółów na temat jego użycia w artykule [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users).

In [120]:
#Inicjalizacja i wypisanie macierzy:
M = np.array([[3, 1, -2, 4], [0, 1, 1, 5], [-2, 1, 1, 5], [4, 3, 0, 1]])
print("Macierz N=\n{0}".format(M))
#Wyciągnięcie elementów o podanych indeksach:
print('\nElement o indeksie 1,1: ', M[0][0])
print('Element o indeksie 3,3: ', M[2][2])
print('Element o indeksie 3,2: ', M[2][1])
#Inicjalizacja oraz wypisanie wektorów:
w1 = M[:,2]
w2 = M[1,:]
print("\nTrzecia kolumna macierzy:\n {0}".format(w1))
print("Drugi wiersz macierzy:\n {0}".format(w2))

Macierz N=
[[ 3  1 -2  4]
 [ 0  1  1  5]
 [-2  1  1  5]
 [ 4  3  0  1]]

Element o indeksie 1,1:  3
Element o indeksie 3,3:  1
Element o indeksie 3,2:  1

Trzecia kolumna macierzy:
 [-2  1  1  0]
Drugi wiersz macierzy:
 [0 1 1 5]


Wniosek:

Utworzenie macierzy za pomocą klasy $array$ pozwala na swobodny dostęp do pojedynczych elementów indeksowaniem - [][], jak i do całych wierszy lub kolumn slicingiem - [:].

***Zadanie 6.***   
Uzupełnij funkcję $custom\_matrix$, tak by parametry m, n określały wymiary macierzy wynikowej, która
będzie wypełniona w/g algorytmu: jeśli indeks wiersza jest większy od indeksu kolumny
wartością komórki jest indeks wiersza, w przeciwnym wypadku wartością komórki jest indeks
kolumny. Funkcja jako wynik powinna zwracać uzupełnioną macierz, jeżeli nie jest to możliwe to powinna zwrócić *None*. Na koniec wyświetlić wynikową macierz dla dowolnych argumentów $m$, $n$ z przedziału $\langle3,7\rangle$.
  
***Wskazówka:*** Inicjalizacja pustej macierz wykonywana jest w pakiecie Numpy przy pomocy funkcji  *[zeros](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)*, zaś macierzy składającej się z jedynek *[ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)*.

In [121]:
zero_matrix = np.zeros((2, 2))
ones_matrix = np.ones((3,1))

print('zero_matrix: \n{}'.format(zero_matrix))
print('ones_matrix: \n{}'.format(ones_matrix))

zero_matrix: 
[[0. 0.]
 [0. 0.]]
ones_matrix: 
[[1.]
 [1.]
 [1.]]


In [122]:
matrix = main.custom_matrix(3, 4)
print('matrix: \n{}'.format(matrix))

matrix = main.custom_matrix(5, -1)
print('\nmatrix: \n{}'.format(matrix))

matrix: 
[[0. 1. 2. 3.]
 [1. 1. 2. 3.]
 [2. 2. 2. 3.]]

matrix: 
None


Wniosek:

Zaimplementowana funkcja poprawnie uzupełnia wcześniej zdefiniowaną macierz według podanego algorytmu, jednak ze względu na jego specyfikę nie pozwala na utworzenie macierzy podając niedodatnie lub wymierne argumenty, zwracając wtedy wartość nieokreśloną None.

***Zadanie 7.***

Biblioteka Numpy posiada własne metody, pozwalające na szybsze i wygotniejsze wykonywanie operacji na wektorach i macierzach. Kolejne zadania mają na celu przećwiczenie tych metod. Zamiast samemu implementować mnożenie macierzy, należy skorzystać właśnie z wbudowanych funkcji Numpy. Najbardzie podstawowe z nich to *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*, *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* oraz *[np.matmul](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.matmul.html)*. Przed wykonaniem zadania należy zapoznać się z ich dokumentacją, aby stosować poprawną funkcję do danego typu mnożenia. Dodatkowo ciekawą i użyteczną funkcjonalnością Numpy, wykorzystywaną niekiedy przy dodawaniu macierzy jest *broadcasting*, proszę o zapoznaie się z opisem:  *[[1]](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html)* *[[2]](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)*.

Zainicjalizować dwa wektory $v_1$ i $v_2$:

$v_1 = \begin{bmatrix}1\\3\\13\end{bmatrix} \quad v_2 = \begin{bmatrix}8\\5\\-2\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $4*v_1$
- $-v_2 + \begin{bmatrix}2\\2\\2\end{bmatrix}$
- $v_1 \circ v_2$ (w sensie mnożenia macierzy, tzw. mnożenie macierzy w sensie Cauchy’ego)
- $v_1 * v_2$ (w sensie mnożenia Hadamarda (element-wise))

***Wskazówki:*** Warto wiedzieć o *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* i *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*. Zbadać jak zachowuje się przeciążony operator mnożenia $*$ oraz $@$ dla macierzy $ndarray$.

In [123]:
#Inicjalizacja wektorów v1 i v2:
v1 = np.array([[1], [3], [13]])
v2 = np.array([[8], [5], [-2]])

#Operacje na wektorach:
v3 = 4 * v1
print("4 * v1: \n", v3)

v4 = -v2 + np.array([[2], [2], [2]])
print("\n-v2 + [2 2 2]: \n", v4)

# v5 = np.matmul(v1, v2)
print("\nv1 v2: Nieprawidłowe dane dla mnożenie w sensie Cauchy'ego.")

v6 = np.multiply(v1, v2)
print("\nv1 * v2: \n", v6)

4 * v1: 
 [[ 4]
 [12]
 [52]]

-v2 + [2 2 2]: 
 [[-6]
 [-3]
 [ 4]]

v1 v2: Nieprawidłowe dane dla mnożenie w sensie Cauchy'ego.

v1 * v2: 
 [[  8]
 [ 15]
 [-26]]


Wniosek:

Definiowanie wektorów za pomocą klasy $array$ pozwala na mnożenie ich różnymi sposobami. W przypadku mnożenia przez skalar oraz dodawania wystarczają zwykłe operatory: * oraz +. Mnożenie w sensie Hadamarda polega na wymnażaniu elementów o odpowiadających sobie indeksach np. za pomocą funkcji multiply. W wypadku mnożenia w sensie Cauchy'ego obiektów z klasy $ndarray$ można zamiennie użyć funkcji $matmul$ lub operatora @. Mnożenie to jednak nie jest dozwolone w każdym przypadku - liczba kolumn pierwszej macierzy oraz wierszy drugiej macierzy muszą być takie same. Z tego powodu nie da się wymnożyć dwóch wektorów kolumnowych w sensie Cauchy'ego.

***Zadanie 8.***
Zainicjalizować macierz $M_1$:

$M_1 = \begin{bmatrix}1&-7&3\\-12&3&4\\5&13&-3\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $3M_1$
- $3M_1 + \begin{bmatrix}1&1&1\\1&1&1\\1&1&1\end{bmatrix}$
- $M_1^T$
- $M_1 \circ v_1$ 
- $v_2^T \circ M_1$

In [124]:
#Inicjalizacja i wypisanie macierzy M1:
M1 = np.array([[1, -7, 3], [-12, 3, 4], [5, 13, -3]])
print("Macierz M1=\n{0}".format(M1))

#Operacje na macierzy M1 i wypisanie ich wyników:
M2 = 3 * M1
print("\n3M1: \n{0}".format(M2))

M3 = M2 + np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
print("\n3M1 + macierz jednostkowa 3x3: \n{0}".format(M3))

M4 = M1.transpose()
print("\nM1': \n{0}".format(M4))

#Inicjalizacja wektorów v1 i v2 z zadania 7:
v1 = np.array([[1], [3], [13]])
v2 = np.array([[8], [5], [-2]])

M5 = np.matmul(M1, v1)
print("\nM1 v1: \n{0}".format(M5))

M6 = np.matmul(v2.transpose(), M1)
print("\nv2' M1': \n{0}".format(M6))

Macierz M1=
[[  1  -7   3]
 [-12   3   4]
 [  5  13  -3]]

3M1: 
[[  3 -21   9]
 [-36   9  12]
 [ 15  39  -9]]

3M1 + macierz jednostkowa 3x3: 
[[  4 -20  10]
 [-35  10  13]
 [ 16  40  -8]]

M1': 
[[  1 -12   5]
 [ -7   3  13]
 [  3   4  -3]]

M1 v1: 
[[19]
 [49]
 [ 5]]

v2' M1': 
[[-62 -67  50]]


Wniosek:

Macierze zdefiniowane za pomocą klasy $ndarray$ zachowują się analogicznie do wektorów z zadania 7. Z powodzeniem można wykonywać na nich operacje mnożenia przez skalar, dodawania, transpozycji oraz mnożenia w sensie Cauchy'ego, jeśli tylko wymiary zadanych macierzy na to pozwalają.

Materiały uzupełniające:
- [Scipy Lecture Notes](http://www.scipy-lectures.org/index.html)
- [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users)
- [Python Tutorial - W3Schools](https://www.w3schools.com/python/default.asp)
- [NumPy](https://www.numpy.org)
- [Matplotlib](https://matplotlib.org/)
- [Anaconda](https://www.anaconda.com/)
- [Learn Python for Data Science](https://www.datacamp.com/learn-python-with-anaconda?utm_source=Anaconda_download&utm_campaign=datacamp_training&utm_medium=banner)
- [Learn Python](https://www.learnpython.org/)
- [Wujek Google](https://google.pl) i [Ciocia Wikipedia](https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna)

Podsumowanie:

Wszystkie funkcje opracowane w pliku main.py z powodzeniem przeszły przewidziane testy jednostkowe.

Zadania zawarte w powyższym skrypcie pozwoliły na zapoznanie się z podstawowymi metodami oraz obiektami biblioteki NumPy. Umożliwia ona m.in. łatwe definiowanie ciągów arytmetycznych (funkcje $arange$ oraz $linspace$) bądź wektorów i macierzy (klasa $ndarray$) w języku Python. Korzystanie z macierzy jako obiektów klasy $ndarray$ pozwala na wykonywanie operacji indeksowania, slicingu i transpozycji oraz podstawowych operacji matematycznych w tym: dodawania oraz różnego rodzaju mnożenia przy zachowaniu odpowiednich wymiarów zadanych macierzy np. dla mnożenia w sensie Cauchy'ego.